config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'welcome/index'

  root 'welcome#index'

  
  resources :users
  resources :phone_numbers

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
	belongs_to :user

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :number, presence: true, numericality: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :authenticate_user!
  before_action :define_phone_number, only: [:show, :destroy, :edit, :update]

  def index
    @phone_numbers = PhoneNumber.accessible_by(current_ability)
  end

  def new
    @phone_number = PhoneNumber.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @phone_number = current_user.phone_numbers.new(phone_number_params)
    
    if @phone_number.save
      flash[:notice] = "New PhoneNumber succesfully added"
    end
    redirect_to '/phone_numbers'
  end

  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  def edit
  end

  def update
  	@phone_number.update(phone_number_params)
    redirect_to '/phone_numbers'
  end

  def destroy
    @phone_number.destroy
    redirect_to '/phone_numbers'
  end

  private

  def define_phone_number
    @phone_number = PhoneNumber.find(params[:id])
  end

  def phone_number_params
    params.require(:phone_number).permit(:name, :address, :companny, :number, :avatar)
  end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.erb
<%= form_for @phone_number, html: { multipart: true } do |f|%>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name'%>
  </div>
  <div class="form-group">
    <%= f.label :number %><br />
    <%= f.text_field :number, autofocus: true, class: 'form-control', placeholder: 'Phone Number'%>
  </div>
  <div class="form-group">
    <%= f.label :companny %><br />
    <%= f.text_field :companny, autofocus: true, class: 'form-control', placeholder: 'Companny Name'%>
  </div>
  <div class="form-group">
    <%= f.label :address %><br />
    <%= f.text_area :address, autofocus: true, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar%>
    <%if @phone_number.avatar.present?%>
      <%= image_tag @phone_number.avatar.url(:thumb) %>
    <%end%>
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
<%end%>

app/views/phone_numbers/_show_detail.html.erb
<div class="team-member">
  <%= image_tag @phone_number.avatar.url(:medium), class: "img-responsive img-circle" %>
  <h4><%= @phone_number.name%></h4>
  <h4><%= @phone_number.number%></h4>
  <p class="text-muted"><%= @phone_number.companny%></p>
  <p class="text-muted"><%= @phone_number.address%></p>

</div>

app/views/phone_numbers/edit.html.erb
<%= render "form" %>

app/views/phone_numbers/index.html.erb
<%= link_to "Add", new_phone_number_path,  class: "btn btn-lg btn-primary", remote: true%>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Phone Number</th>
			<th>Companny</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	  <% @phone_numbers.each do |contact|%>
      <tr>
        <td><%= link_to contact.name, phone_number_path(contact), remote: true %></td>
        <td><%= contact.number%></td>
        <td><%= contact.companny%></td>
        <td>
          <% if can? :update, contact %>
            <%= link_to edit_phone_number_path(contact), class: "btn btn-default" do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
          <% end %>

          <%= link_to phone_number_path(contact), method: :delete,class: "btn btn-default" do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
	  <%end%>

	</tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Contact</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/phone_numbers/new.html.erb
<%= render "form" %>

app/views/phone_numbers/new.js.erb
$('.modal-body').html("<%= escape_javascript render(partial: 'form') %>");
$('#myModal').modal('show');

app/views/phone_numbers/show.html.erb
<div class="col-sm-4">
</div>
<div class="col-sm-4">
  <%= render "show_detail" %>
</div>

app/views/phone_numbers/show.js.erb
$('.modal-body').html("<%= escape_javascript render(partial: 'show_detail') %>");
$('.modal-header').hide();
$('#myModal').modal('show');