config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'welcome/index'

  root 'welcome#index'

  
  resources :users
  resources :phone_numbers

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%#= javascript_include_tag :defaults %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container">
		    <div class="navbar-header">
		      <%= link_to 'My Phonebook', root_path, class: 'navbar-brand' %>
		    </div>
		    <div id="navbar">
		      <ul class="nav navbar-nav">
		        <li><%= link_to 'Home', root_path %></li>
		        <li><%= link_to 'Phone Book', phone_numbers_path %></li>
		      </ul>
		      <ul class="nav navbar-nav pull-right">
		        <% if user_signed_in? %>
		          <li class="dropdown">
		            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
		              <%= current_user.email %>
		              <span class="caret"></span>
		            </a>
		            <ul class="dropdown-menu" role="menu">
		              <li><%= link_to 'Profile', edit_user_registration_path %></li>
		              <li><%= link_to 'Log out', destroy_user_session_path %></li>
		            </ul>
		          </li>
		        <% else %>
		          <li><%= link_to 'Log In', new_user_session_path %></li>
		          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
		        <% end %>
		      </ul>
		    </div>
		  </div>
		</nav>
    <div class="container theme-showcase" role="main">
	   
      <p class="notice"><%= notice %></p>
	    <p class="alert"><%= alert %></p>
	    <%= yield %>
    </div>
  </body>
</html>